name: Deploy Frontend (Angular)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no deploy@72.60.2.46 << 'EOF'
            set -e

            # Variáveis
            APP_DIR=\$HOME/PatientManagementFrontEnd
            WWW_DIR=/var/www/patient-frontend

            echo "🔁 Limpando repositório antigo (se existir)..."
            rm -rf \$APP_DIR

            echo "📥 Clonando projeto..."
            git clone https://github.com/matheuskieling/PatientManagementFrontEnd.git \$APP_DIR

            echo "📦 Instalando dependências e buildando..."
            cd \$APP_DIR
            export NVM_DIR="\$HOME/.nvm"
            source \$NVM_DIR/nvm.sh
            nvm install 22.17.0
            nvm use 22.17.0
            npm ci
            npm run build --configuration=production

            echo "🚚 Copiando arquivos para Nginx..."
            sudo rm -rf \$WWW_DIR/*
            sudo cp -r dist/patient-management-front-end/* \$WWW_DIR
            sudo chown -R www-data:www-data \$WWW_DIR

            echo "✅ Reload Nginx"
            sudo nginx -t && sudo systemctl reload nginx

            echo "✅ Deploy concluído com sucesso!"
          EOF
