name: Deploy Frontend (Angular)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no deploy@72.60.2.46 << 'EOF'
            set -e

            echo "🔁 Removendo repositório antigo..."
            rm -rf PatientManagementFrontEnd

            echo "📥 Clonando repositório..."
            git clone https://github.com/matheuskieling/PatientManagementFrontEnd.git /home/deploy/PatientManagementFrontEnd

            echo "📦 Instalando dependências e buildando..."
            cd PatientManagementFrontEnd
            export NVM_DIR="\$HOME/.nvm"
            source \$NVM_DIR/nvm.sh
            nvm install 22.17.0
            nvm use 22.17.0
            npm ci
            npm run build --configuration=production

            echo "🚚 Copiando arquivos para o Nginx..."
            sudo rm -rf /var/www/patient-frontend/*
            sudo cp -r dist/patient-management-front-end/* /var/www/patient-frontend
            sudo chown -R www-data:www-data /var/www/patient-frontend

            echo "✅ Reiniciando Nginx"
            sudo nginx -t && sudo systemctl reload nginx

            echo "✅ Deploy concluído com sucesso!"
          EOF
